# Generated by scripts/generate.mjs. Do not edit.
from __future__ import annotations
from typing import Literal
from .runtime import Response, SyncTransport, AsyncTransport
from ._generated.types import UNSET, Unset
from ._generated.api.default import get_profile_posts as m_get_profile_posts
from ._generated.api.default import get_profile_comments as m_get_profile_comments
from ._generated.api.default import get_profile_reactions as m_get_profile_reactions
from ._generated.api.default import get_similar_profiles as m_get_similar_profiles
from ._generated.api.default import get_company_posts as m_get_company_posts
from ._generated.api.default import get_company_people as m_get_company_people
from ._generated.api.default import get_company_products as m_get_company_products
from ._generated.api.default import get_company_jobs as m_get_company_jobs
from ._generated.api.default import (
    search_companies_by_domain as m_search_companies_by_domain,
)
from ._generated.api.default import (
    search_companies_by_keyword as m_search_companies_by_keyword,
)
from ._generated.api.default import (
    search_schools_by_keyword as m_search_schools_by_keyword,
)
from ._generated.api.default import (
    search_people_by_keyword as m_search_people_by_keyword,
)
from ._generated.api.default import (
    search_all_results_by_keyword as m_search_all_results_by_keyword,
)
from ._generated.api.default import search_posts_by_hashtag as m_search_posts_by_hashtag
from ._generated.api.default import search_posts_by_keyword as m_search_posts_by_keyword
from ._generated.api.default import (
    search_locations_by_keyword as m_search_locations_by_keyword,
)
from ._generated.api.default import (
    search_industries_by_keyword as m_search_industries_by_keyword,
)
from ._generated.api.default import (
    search_service_categories as m_search_service_categories,
)
from ._generated.api.default import get_search_typeahead as m_get_search_typeahead
from ._generated.api.default import search_jobs as m_search_jobs
from ._generated.api.default import get_job_details as m_get_job_details
from ._generated.api.default import (
    get_profile_details_by_url as m_get_profile_details_by_url,
)
from ._generated.api.default import (
    get_profile_details_by_username as m_get_profile_details_by_username,
)
from ._generated.api.default import (
    get_profile_details_by_id as m_get_profile_details_by_id,
)
from ._generated.api.default import (
    get_company_details_by_url as m_get_company_details_by_url,
)
from ._generated.api.default import (
    get_company_details_by_slug as m_get_company_details_by_slug,
)
from ._generated.api.default import (
    get_company_details_by_id as m_get_company_details_by_id,
)
from ._generated.api.default import (
    get_profile_contact_by_url as m_get_profile_contact_by_url,
)
from ._generated.api.default import (
    get_profile_contact_by_username as m_get_profile_contact_by_username,
)
from ._generated.api.default import (
    get_profile_full_experience_by_url as m_get_profile_full_experience_by_url,
)
from ._generated.api.default import (
    get_profile_full_experience_by_username as m_get_profile_full_experience_by_username,
)
from ._generated.api.default import (
    get_profile_education_by_url as m_get_profile_education_by_url,
)
from ._generated.api.default import (
    get_profile_education_by_username as m_get_profile_education_by_username,
)
from ._generated.api.default import (
    get_profile_skills_by_url as m_get_profile_skills_by_url,
)
from ._generated.api.default import (
    get_profile_skills_by_username as m_get_profile_skills_by_username,
)
from ._generated.api.default import (
    get_profile_certifications_by_url as m_get_profile_certifications_by_url,
)
from ._generated.api.default import (
    get_profile_certifications_by_username as m_get_profile_certifications_by_username,
)
from ._generated.api.default import (
    get_profile_courses_by_url as m_get_profile_courses_by_url,
)
from ._generated.api.default import (
    get_profile_courses_by_username as m_get_profile_courses_by_username,
)
from ._generated.api.default import (
    get_profile_company_interests_by_url as m_get_profile_company_interests_by_url,
)
from ._generated.api.default import (
    get_profile_company_interests_by_username as m_get_profile_company_interests_by_username,
)
from ._generated.api.default import (
    get_profile_company_interests_by_id as m_get_profile_company_interests_by_id,
)
from ._generated.api.default import (
    get_profile_volunteer_experience_by_url as m_get_profile_volunteer_experience_by_url,
)
from ._generated.api.default import (
    get_profile_volunteer_experience_by_username as m_get_profile_volunteer_experience_by_username,
)
from ._generated.api.default import get_post_by_url as m_get_post_by_url
from ._generated.api.default import get_post_by_slug as m_get_post_by_slug
from ._generated.api.default import (
    get_post_comments_by_url as m_get_post_comments_by_url,
)
from ._generated.api.default import (
    get_post_comments_by_slug as m_get_post_comments_by_slug,
)
from ._generated.api.default import (
    get_post_reactions_by_url as m_get_post_reactions_by_url,
)
from ._generated.api.default import (
    get_post_reactions_by_slug as m_get_post_reactions_by_slug,
)
from ._generated.api.default import (
    get_similar_companies_by_url as m_get_similar_companies_by_url,
)
from ._generated.api.default import (
    get_similar_companies_by_slug as m_get_similar_companies_by_slug,
)


class Profiles:
    def __init__(self, owner: SyncTransport):
        self._owner = owner

    def get_posts(
        self,
        *,
        username: str,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_profile_posts.ProfilePostsSuccess]:
        return self._owner._request(
            m_get_profile_posts.ProfilePostsSuccess,
            m_get_profile_posts._get_kwargs(username=username, cursor=cursor),
        )

    def get_comments(
        self,
        *,
        username: str,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_profile_comments.ProfileCommentsSuccess]:
        return self._owner._request(
            m_get_profile_comments.ProfileCommentsSuccess,
            m_get_profile_comments._get_kwargs(username=username, cursor=cursor),
        )

    def get_reactions(
        self,
        *,
        username: str,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_profile_reactions.ProfileReactionsSuccess]:
        return self._owner._request(
            m_get_profile_reactions.ProfileReactionsSuccess,
            m_get_profile_reactions._get_kwargs(username=username, cursor=cursor),
        )

    def get_similar(
        self,
        *,
        username: str,
    ) -> Response[m_get_similar_profiles.SimilarProfilesSuccess]:
        return self._owner._request(
            m_get_similar_profiles.SimilarProfilesSuccess,
            m_get_similar_profiles._get_kwargs(username=username),
        )

    def search_by_keyword(
        self,
        *,
        keywords: str,
        location: str | Unset = UNSET,
        current_company: str | Unset = UNSET,
        past_company: str | Unset = UNSET,
        school_filter: str | Unset = UNSET,
        profile_language: str | Unset = UNSET,
        service_category: str | Unset = UNSET,
        industry: str | Unset = UNSET,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_people_by_keyword.PeopleKeywordSearchSuccess]:
        return self._owner._request(
            m_search_people_by_keyword.PeopleKeywordSearchSuccess,
            m_search_people_by_keyword._get_kwargs(
                keywords=keywords,
                location=location,
                current_company=current_company,
                past_company=past_company,
                school_filter=school_filter,
                profile_language=profile_language,
                service_category=service_category,
                industry=industry,
                offset=offset,
            ),
        )

    def get_details_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_details_by_url.ProfileSuccess]:
        return self._owner._request(
            m_get_profile_details_by_url.ProfileSuccess,
            m_get_profile_details_by_url._get_kwargs(url_query=url),
        )

    def get_details_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_details_by_username.ProfileSuccess]:
        return self._owner._request(
            m_get_profile_details_by_username.ProfileSuccess,
            m_get_profile_details_by_username._get_kwargs(username=username),
        )

    def get_details_by_id(
        self,
        *,
        public_id: str,
    ) -> Response[m_get_profile_details_by_id.ProfileSuccess]:
        return self._owner._request(
            m_get_profile_details_by_id.ProfileSuccess,
            m_get_profile_details_by_id._get_kwargs(public_id=public_id),
        )

    def get_contact_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_contact_by_url.ProfileContactSuccess]:
        return self._owner._request(
            m_get_profile_contact_by_url.ProfileContactSuccess,
            m_get_profile_contact_by_url._get_kwargs(url_query=url),
        )

    def get_contact_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_contact_by_username.ProfileContactSuccess]:
        return self._owner._request(
            m_get_profile_contact_by_username.ProfileContactSuccess,
            m_get_profile_contact_by_username._get_kwargs(username=username),
        )

    def get_full_experience_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_full_experience_by_url.ProfileExperienceSuccess]:
        return self._owner._request(
            m_get_profile_full_experience_by_url.ProfileExperienceSuccess,
            m_get_profile_full_experience_by_url._get_kwargs(url_query=url),
        )

    def get_full_experience_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_full_experience_by_username.ProfileExperienceSuccess]:
        return self._owner._request(
            m_get_profile_full_experience_by_username.ProfileExperienceSuccess,
            m_get_profile_full_experience_by_username._get_kwargs(username=username),
        )

    def get_education_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_education_by_url.ProfileEducationSuccess]:
        return self._owner._request(
            m_get_profile_education_by_url.ProfileEducationSuccess,
            m_get_profile_education_by_url._get_kwargs(url_query=url),
        )

    def get_education_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_education_by_username.ProfileEducationSuccess]:
        return self._owner._request(
            m_get_profile_education_by_username.ProfileEducationSuccess,
            m_get_profile_education_by_username._get_kwargs(username=username),
        )

    def get_skills_by_url(
        self,
        *,
        url: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_profile_skills_by_url.ProfileSkillsSuccess]:
        return self._owner._request(
            m_get_profile_skills_by_url.ProfileSkillsSuccess,
            m_get_profile_skills_by_url._get_kwargs(url_query=url, start=start),
        )

    def get_skills_by_username(
        self,
        *,
        username: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_profile_skills_by_username.ProfileSkillsSuccess]:
        return self._owner._request(
            m_get_profile_skills_by_username.ProfileSkillsSuccess,
            m_get_profile_skills_by_username._get_kwargs(
                username=username, start=start
            ),
        )

    def get_certifications_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_certifications_by_url.ProfileCertificationsSuccess]:
        return self._owner._request(
            m_get_profile_certifications_by_url.ProfileCertificationsSuccess,
            m_get_profile_certifications_by_url._get_kwargs(url_query=url),
        )

    def get_certifications_by_username(
        self,
        *,
        username: str,
    ) -> Response[
        m_get_profile_certifications_by_username.ProfileCertificationsSuccess
    ]:
        return self._owner._request(
            m_get_profile_certifications_by_username.ProfileCertificationsSuccess,
            m_get_profile_certifications_by_username._get_kwargs(username=username),
        )

    def get_courses_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_courses_by_url.ProfileCoursesSuccess]:
        return self._owner._request(
            m_get_profile_courses_by_url.ProfileCoursesSuccess,
            m_get_profile_courses_by_url._get_kwargs(url_query=url),
        )

    def get_courses_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_courses_by_username.ProfileCoursesSuccess]:
        return self._owner._request(
            m_get_profile_courses_by_username.ProfileCoursesSuccess,
            m_get_profile_courses_by_username._get_kwargs(username=username),
        )

    def get_company_interests_by_url(
        self,
        *,
        url: str,
        start: int | Unset = UNSET,
    ) -> Response[
        m_get_profile_company_interests_by_url.ProfileCompanyInterestsSuccess
    ]:
        return self._owner._request(
            m_get_profile_company_interests_by_url.ProfileCompanyInterestsSuccess,
            m_get_profile_company_interests_by_url._get_kwargs(
                url_query=url, start=start
            ),
        )

    def get_company_interests_by_username(
        self,
        *,
        username: str,
        start: int | Unset = UNSET,
    ) -> Response[
        m_get_profile_company_interests_by_username.ProfileCompanyInterestsSuccess
    ]:
        return self._owner._request(
            m_get_profile_company_interests_by_username.ProfileCompanyInterestsSuccess,
            m_get_profile_company_interests_by_username._get_kwargs(
                username=username, start=start
            ),
        )

    def get_company_interests_by_id(
        self,
        *,
        public_id: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_profile_company_interests_by_id.ProfileCompanyInterestsSuccess]:
        return self._owner._request(
            m_get_profile_company_interests_by_id.ProfileCompanyInterestsSuccess,
            m_get_profile_company_interests_by_id._get_kwargs(
                public_id=public_id, start=start
            ),
        )

    def get_volunteer_experience_by_url(
        self,
        *,
        url: str,
    ) -> Response[
        m_get_profile_volunteer_experience_by_url.ProfileVolunteerExperienceSuccess
    ]:
        return self._owner._request(
            m_get_profile_volunteer_experience_by_url.ProfileVolunteerExperienceSuccess,
            m_get_profile_volunteer_experience_by_url._get_kwargs(url_query=url),
        )

    def get_volunteer_experience_by_username(
        self,
        *,
        username: str,
    ) -> Response[
        m_get_profile_volunteer_experience_by_username.ProfileVolunteerExperienceSuccess
    ]:
        return self._owner._request(
            m_get_profile_volunteer_experience_by_username.ProfileVolunteerExperienceSuccess,
            m_get_profile_volunteer_experience_by_username._get_kwargs(
                username=username
            ),
        )


class Companies:
    def __init__(self, owner: SyncTransport):
        self._owner = owner

    def get_posts(
        self,
        *,
        slug: str,
        filter_: m_get_company_posts.GetCompanyPostsFilter | Unset = UNSET,
        start: int | Unset = UNSET,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_company_posts.CompanyPostsSuccess]:
        return self._owner._request(
            m_get_company_posts.CompanyPostsSuccess,
            m_get_company_posts._get_kwargs(
                slug=slug, filter_=filter_, start=start, cursor=cursor
            ),
        )

    def get_people(
        self,
        *,
        slug: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_company_people.CompanyPeopleSuccess]:
        return self._owner._request(
            m_get_company_people.CompanyPeopleSuccess,
            m_get_company_people._get_kwargs(slug=slug, start=start),
        )

    def get_products(
        self,
        *,
        slug: str,
        state: m_get_company_products.GetCompanyProductsState | Unset = UNSET,
        start: int | Unset = UNSET,
    ) -> Response[m_get_company_products.LinkedInV2CompanyProductsSuccess]:
        return self._owner._request(
            m_get_company_products.LinkedInV2CompanyProductsSuccess,
            m_get_company_products._get_kwargs(slug=slug, state=state, start=start),
        )

    def get_jobs(
        self,
        *,
        slug: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_company_jobs.CompanyJobsSuccess]:
        return self._owner._request(
            m_get_company_jobs.CompanyJobsSuccess,
            m_get_company_jobs._get_kwargs(slug=slug, start=start),
        )

    def search_by_domain(
        self,
        *,
        domain: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_companies_by_domain.CompanyDomainSearchSuccess]:
        return self._owner._request(
            m_search_companies_by_domain.CompanyDomainSearchSuccess,
            m_search_companies_by_domain._get_kwargs(domain=domain, offset=offset),
        )

    def search_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
        location: str | Unset = UNSET,
        industry: str | Unset = UNSET,
        company_size: str | Unset = UNSET,
        has_jobs: Literal["true"] | Unset = UNSET,
    ) -> Response[m_search_companies_by_keyword.CompanyDomainSearchSuccess]:
        return self._owner._request(
            m_search_companies_by_keyword.CompanyDomainSearchSuccess,
            m_search_companies_by_keyword._get_kwargs(
                keywords=keywords,
                offset=offset,
                location=location,
                industry=industry,
                company_size=company_size,
                has_jobs=has_jobs,
            ),
        )

    def get_details_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_company_details_by_url.CompanySuccess]:
        return self._owner._request(
            m_get_company_details_by_url.CompanySuccess,
            m_get_company_details_by_url._get_kwargs(url_query=url),
        )

    def get_details_by_slug(
        self,
        *,
        slug: str,
    ) -> Response[m_get_company_details_by_slug.CompanySuccess]:
        return self._owner._request(
            m_get_company_details_by_slug.CompanySuccess,
            m_get_company_details_by_slug._get_kwargs(slug=slug),
        )

    def get_details_by_id(
        self,
        *,
        public_id: str,
    ) -> Response[m_get_company_details_by_id.CompanySuccess]:
        return self._owner._request(
            m_get_company_details_by_id.CompanySuccess,
            m_get_company_details_by_id._get_kwargs(public_id=public_id),
        )

    def get_similar_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_similar_companies_by_url.SimilarCompaniesSuccess]:
        return self._owner._request(
            m_get_similar_companies_by_url.SimilarCompaniesSuccess,
            m_get_similar_companies_by_url._get_kwargs(url_query=url),
        )

    def get_similar_by_slug(
        self,
        *,
        slug: str,
    ) -> Response[m_get_similar_companies_by_slug.SimilarCompaniesSuccess]:
        return self._owner._request(
            m_get_similar_companies_by_slug.SimilarCompaniesSuccess,
            m_get_similar_companies_by_slug._get_kwargs(slug=slug),
        )


class Schools:
    def __init__(self, owner: SyncTransport):
        self._owner = owner

    def search_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_schools_by_keyword.LinkedInV2SchoolSearchSuccess]:
        return self._owner._request(
            m_search_schools_by_keyword.LinkedInV2SchoolSearchSuccess,
            m_search_schools_by_keyword._get_kwargs(keywords=keywords, offset=offset),
        )


class Search:
    def __init__(self, owner: SyncTransport):
        self._owner = owner

    def search_all_results_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_all_results_by_keyword.KeywordSearchSuccess]:
        return self._owner._request(
            m_search_all_results_by_keyword.KeywordSearchSuccess,
            m_search_all_results_by_keyword._get_kwargs(
                keywords=keywords, offset=offset
            ),
        )

    def search_posts_by_hashtag(
        self,
        *,
        hashtag: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_posts_by_hashtag.HashtagPostsSearchSuccess]:
        return self._owner._request(
            m_search_posts_by_hashtag.HashtagPostsSearchSuccess,
            m_search_posts_by_hashtag._get_kwargs(hashtag=hashtag, offset=offset),
        )

    def search_posts_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
        sort: m_search_posts_by_keyword.SearchPostsByKeywordSort | Unset = UNSET,
        posted_within: m_search_posts_by_keyword.SearchPostsByKeywordPostedWithin
        | Unset = UNSET,
        content_type: m_search_posts_by_keyword.SearchPostsByKeywordContentType
        | Unset = UNSET,
    ) -> Response[m_search_posts_by_keyword.LinkedInV2SearchPostsSuccess]:
        return self._owner._request(
            m_search_posts_by_keyword.LinkedInV2SearchPostsSuccess,
            m_search_posts_by_keyword._get_kwargs(
                keywords=keywords,
                offset=offset,
                sort=sort,
                posted_within=posted_within,
                content_type=content_type,
            ),
        )

    def search_locations_by_keyword(
        self,
        *,
        keywords: str,
    ) -> Response[m_search_locations_by_keyword.LinkedInV2LocationSearchSuccess]:
        return self._owner._request(
            m_search_locations_by_keyword.LinkedInV2LocationSearchSuccess,
            m_search_locations_by_keyword._get_kwargs(keywords=keywords),
        )

    def search_industries_by_keyword(
        self,
        *,
        query: str,
    ) -> Response[m_search_industries_by_keyword.IndustrySearchSuccess]:
        return self._owner._request(
            m_search_industries_by_keyword.IndustrySearchSuccess,
            m_search_industries_by_keyword._get_kwargs(query=query),
        )

    def search_service_categories(
        self,
        *,
        query: str | Unset = UNSET,
    ) -> Response[m_search_service_categories.LinkedInV2ServiceCategorySearchSuccess]:
        return self._owner._request(
            m_search_service_categories.LinkedInV2ServiceCategorySearchSuccess,
            m_search_service_categories._get_kwargs(query=query),
        )

    def get_typeahead(
        self,
        *,
        query: str,
    ) -> Response[m_get_search_typeahead.LinkedInV2SearchTypeaheadSuccess]:
        return self._owner._request(
            m_get_search_typeahead.LinkedInV2SearchTypeaheadSuccess,
            m_get_search_typeahead._get_kwargs(query=query),
        )


class Jobs:
    def __init__(self, owner: SyncTransport):
        self._owner = owner

    def search(
        self,
        *,
        keywords: str,
        start: int | Unset = UNSET,
        location: str | Unset = UNSET,
        company_slug: str | Unset = UNSET,
        experience: m_search_jobs.SearchJobsExperience | Unset = UNSET,
        sort: m_search_jobs.SearchJobsSort | Unset = UNSET,
        time_posted: m_search_jobs.SearchJobsTimePosted | Unset = UNSET,
    ) -> Response[m_search_jobs.JobSearchSuccess]:
        return self._owner._request(
            m_search_jobs.JobSearchSuccess,
            m_search_jobs._get_kwargs(
                keywords=keywords,
                start=start,
                location=location,
                company_slug=company_slug,
                experience=experience,
                sort=sort,
                time_posted=time_posted,
            ),
        )

    def get_details(
        self,
        *,
        url: str,
    ) -> Response[m_get_job_details.JobDetailsSuccess]:
        return self._owner._request(
            m_get_job_details.JobDetailsSuccess,
            m_get_job_details._get_kwargs(url_query=url),
        )


class Posts:
    def __init__(self, owner: SyncTransport):
        self._owner = owner

    def get_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_post_by_url.LinkedInV2PostSuccess]:
        return self._owner._request(
            m_get_post_by_url.LinkedInV2PostSuccess,
            m_get_post_by_url._get_kwargs(url_query=url),
        )

    def get_by_slug(
        self,
        *,
        slug: str,
    ) -> Response[m_get_post_by_slug.LinkedInV2PostSuccess]:
        return self._owner._request(
            m_get_post_by_slug.LinkedInV2PostSuccess,
            m_get_post_by_slug._get_kwargs(slug=slug),
        )

    def get_comments_by_url(
        self,
        *,
        url: str,
        sort_order: m_get_post_comments_by_url.GetPostCommentsByUrlSortOrder
        | Unset = UNSET,
    ) -> Response[m_get_post_comments_by_url.LinkedInV2PostCommentsSuccess]:
        return self._owner._request(
            m_get_post_comments_by_url.LinkedInV2PostCommentsSuccess,
            m_get_post_comments_by_url._get_kwargs(
                url_query=url, sort_order=sort_order
            ),
        )

    def get_comments_by_slug(
        self,
        *,
        slug: str,
        sort_order: m_get_post_comments_by_slug.GetPostCommentsBySlugSortOrder
        | Unset = UNSET,
    ) -> Response[m_get_post_comments_by_slug.LinkedInV2PostCommentsSuccess]:
        return self._owner._request(
            m_get_post_comments_by_slug.LinkedInV2PostCommentsSuccess,
            m_get_post_comments_by_slug._get_kwargs(slug=slug, sort_order=sort_order),
        )

    def get_reactions_by_url(
        self,
        *,
        url: str,
        reaction_type: m_get_post_reactions_by_url.GetPostReactionsByUrlReactionType,
    ) -> Response[m_get_post_reactions_by_url.LinkedInV2PostReactionsSuccess]:
        return self._owner._request(
            m_get_post_reactions_by_url.LinkedInV2PostReactionsSuccess,
            m_get_post_reactions_by_url._get_kwargs(
                url_query=url, reaction_type=reaction_type
            ),
        )

    def get_reactions_by_slug(
        self,
        *,
        slug: str,
        reaction_type: m_get_post_reactions_by_slug.GetPostReactionsBySlugReactionType,
    ) -> Response[m_get_post_reactions_by_slug.LinkedInV2PostReactionsSuccess]:
        return self._owner._request(
            m_get_post_reactions_by_slug.LinkedInV2PostReactionsSuccess,
            m_get_post_reactions_by_slug._get_kwargs(
                slug=slug, reaction_type=reaction_type
            ),
        )


class AsyncProfiles:
    def __init__(self, owner: AsyncTransport):
        self._owner = owner

    async def get_posts(
        self,
        *,
        username: str,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_profile_posts.ProfilePostsSuccess]:
        return await self._owner._request(
            m_get_profile_posts.ProfilePostsSuccess,
            m_get_profile_posts._get_kwargs(username=username, cursor=cursor),
        )

    async def get_comments(
        self,
        *,
        username: str,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_profile_comments.ProfileCommentsSuccess]:
        return await self._owner._request(
            m_get_profile_comments.ProfileCommentsSuccess,
            m_get_profile_comments._get_kwargs(username=username, cursor=cursor),
        )

    async def get_reactions(
        self,
        *,
        username: str,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_profile_reactions.ProfileReactionsSuccess]:
        return await self._owner._request(
            m_get_profile_reactions.ProfileReactionsSuccess,
            m_get_profile_reactions._get_kwargs(username=username, cursor=cursor),
        )

    async def get_similar(
        self,
        *,
        username: str,
    ) -> Response[m_get_similar_profiles.SimilarProfilesSuccess]:
        return await self._owner._request(
            m_get_similar_profiles.SimilarProfilesSuccess,
            m_get_similar_profiles._get_kwargs(username=username),
        )

    async def search_by_keyword(
        self,
        *,
        keywords: str,
        location: str | Unset = UNSET,
        current_company: str | Unset = UNSET,
        past_company: str | Unset = UNSET,
        school_filter: str | Unset = UNSET,
        profile_language: str | Unset = UNSET,
        service_category: str | Unset = UNSET,
        industry: str | Unset = UNSET,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_people_by_keyword.PeopleKeywordSearchSuccess]:
        return await self._owner._request(
            m_search_people_by_keyword.PeopleKeywordSearchSuccess,
            m_search_people_by_keyword._get_kwargs(
                keywords=keywords,
                location=location,
                current_company=current_company,
                past_company=past_company,
                school_filter=school_filter,
                profile_language=profile_language,
                service_category=service_category,
                industry=industry,
                offset=offset,
            ),
        )

    async def get_details_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_details_by_url.ProfileSuccess]:
        return await self._owner._request(
            m_get_profile_details_by_url.ProfileSuccess,
            m_get_profile_details_by_url._get_kwargs(url_query=url),
        )

    async def get_details_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_details_by_username.ProfileSuccess]:
        return await self._owner._request(
            m_get_profile_details_by_username.ProfileSuccess,
            m_get_profile_details_by_username._get_kwargs(username=username),
        )

    async def get_details_by_id(
        self,
        *,
        public_id: str,
    ) -> Response[m_get_profile_details_by_id.ProfileSuccess]:
        return await self._owner._request(
            m_get_profile_details_by_id.ProfileSuccess,
            m_get_profile_details_by_id._get_kwargs(public_id=public_id),
        )

    async def get_contact_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_contact_by_url.ProfileContactSuccess]:
        return await self._owner._request(
            m_get_profile_contact_by_url.ProfileContactSuccess,
            m_get_profile_contact_by_url._get_kwargs(url_query=url),
        )

    async def get_contact_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_contact_by_username.ProfileContactSuccess]:
        return await self._owner._request(
            m_get_profile_contact_by_username.ProfileContactSuccess,
            m_get_profile_contact_by_username._get_kwargs(username=username),
        )

    async def get_full_experience_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_full_experience_by_url.ProfileExperienceSuccess]:
        return await self._owner._request(
            m_get_profile_full_experience_by_url.ProfileExperienceSuccess,
            m_get_profile_full_experience_by_url._get_kwargs(url_query=url),
        )

    async def get_full_experience_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_full_experience_by_username.ProfileExperienceSuccess]:
        return await self._owner._request(
            m_get_profile_full_experience_by_username.ProfileExperienceSuccess,
            m_get_profile_full_experience_by_username._get_kwargs(username=username),
        )

    async def get_education_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_education_by_url.ProfileEducationSuccess]:
        return await self._owner._request(
            m_get_profile_education_by_url.ProfileEducationSuccess,
            m_get_profile_education_by_url._get_kwargs(url_query=url),
        )

    async def get_education_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_education_by_username.ProfileEducationSuccess]:
        return await self._owner._request(
            m_get_profile_education_by_username.ProfileEducationSuccess,
            m_get_profile_education_by_username._get_kwargs(username=username),
        )

    async def get_skills_by_url(
        self,
        *,
        url: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_profile_skills_by_url.ProfileSkillsSuccess]:
        return await self._owner._request(
            m_get_profile_skills_by_url.ProfileSkillsSuccess,
            m_get_profile_skills_by_url._get_kwargs(url_query=url, start=start),
        )

    async def get_skills_by_username(
        self,
        *,
        username: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_profile_skills_by_username.ProfileSkillsSuccess]:
        return await self._owner._request(
            m_get_profile_skills_by_username.ProfileSkillsSuccess,
            m_get_profile_skills_by_username._get_kwargs(
                username=username, start=start
            ),
        )

    async def get_certifications_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_certifications_by_url.ProfileCertificationsSuccess]:
        return await self._owner._request(
            m_get_profile_certifications_by_url.ProfileCertificationsSuccess,
            m_get_profile_certifications_by_url._get_kwargs(url_query=url),
        )

    async def get_certifications_by_username(
        self,
        *,
        username: str,
    ) -> Response[
        m_get_profile_certifications_by_username.ProfileCertificationsSuccess
    ]:
        return await self._owner._request(
            m_get_profile_certifications_by_username.ProfileCertificationsSuccess,
            m_get_profile_certifications_by_username._get_kwargs(username=username),
        )

    async def get_courses_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_profile_courses_by_url.ProfileCoursesSuccess]:
        return await self._owner._request(
            m_get_profile_courses_by_url.ProfileCoursesSuccess,
            m_get_profile_courses_by_url._get_kwargs(url_query=url),
        )

    async def get_courses_by_username(
        self,
        *,
        username: str,
    ) -> Response[m_get_profile_courses_by_username.ProfileCoursesSuccess]:
        return await self._owner._request(
            m_get_profile_courses_by_username.ProfileCoursesSuccess,
            m_get_profile_courses_by_username._get_kwargs(username=username),
        )

    async def get_company_interests_by_url(
        self,
        *,
        url: str,
        start: int | Unset = UNSET,
    ) -> Response[
        m_get_profile_company_interests_by_url.ProfileCompanyInterestsSuccess
    ]:
        return await self._owner._request(
            m_get_profile_company_interests_by_url.ProfileCompanyInterestsSuccess,
            m_get_profile_company_interests_by_url._get_kwargs(
                url_query=url, start=start
            ),
        )

    async def get_company_interests_by_username(
        self,
        *,
        username: str,
        start: int | Unset = UNSET,
    ) -> Response[
        m_get_profile_company_interests_by_username.ProfileCompanyInterestsSuccess
    ]:
        return await self._owner._request(
            m_get_profile_company_interests_by_username.ProfileCompanyInterestsSuccess,
            m_get_profile_company_interests_by_username._get_kwargs(
                username=username, start=start
            ),
        )

    async def get_company_interests_by_id(
        self,
        *,
        public_id: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_profile_company_interests_by_id.ProfileCompanyInterestsSuccess]:
        return await self._owner._request(
            m_get_profile_company_interests_by_id.ProfileCompanyInterestsSuccess,
            m_get_profile_company_interests_by_id._get_kwargs(
                public_id=public_id, start=start
            ),
        )

    async def get_volunteer_experience_by_url(
        self,
        *,
        url: str,
    ) -> Response[
        m_get_profile_volunteer_experience_by_url.ProfileVolunteerExperienceSuccess
    ]:
        return await self._owner._request(
            m_get_profile_volunteer_experience_by_url.ProfileVolunteerExperienceSuccess,
            m_get_profile_volunteer_experience_by_url._get_kwargs(url_query=url),
        )

    async def get_volunteer_experience_by_username(
        self,
        *,
        username: str,
    ) -> Response[
        m_get_profile_volunteer_experience_by_username.ProfileVolunteerExperienceSuccess
    ]:
        return await self._owner._request(
            m_get_profile_volunteer_experience_by_username.ProfileVolunteerExperienceSuccess,
            m_get_profile_volunteer_experience_by_username._get_kwargs(
                username=username
            ),
        )


class AsyncCompanies:
    def __init__(self, owner: AsyncTransport):
        self._owner = owner

    async def get_posts(
        self,
        *,
        slug: str,
        filter_: m_get_company_posts.GetCompanyPostsFilter | Unset = UNSET,
        start: int | Unset = UNSET,
        cursor: str | Unset = UNSET,
    ) -> Response[m_get_company_posts.CompanyPostsSuccess]:
        return await self._owner._request(
            m_get_company_posts.CompanyPostsSuccess,
            m_get_company_posts._get_kwargs(
                slug=slug, filter_=filter_, start=start, cursor=cursor
            ),
        )

    async def get_people(
        self,
        *,
        slug: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_company_people.CompanyPeopleSuccess]:
        return await self._owner._request(
            m_get_company_people.CompanyPeopleSuccess,
            m_get_company_people._get_kwargs(slug=slug, start=start),
        )

    async def get_products(
        self,
        *,
        slug: str,
        state: m_get_company_products.GetCompanyProductsState | Unset = UNSET,
        start: int | Unset = UNSET,
    ) -> Response[m_get_company_products.LinkedInV2CompanyProductsSuccess]:
        return await self._owner._request(
            m_get_company_products.LinkedInV2CompanyProductsSuccess,
            m_get_company_products._get_kwargs(slug=slug, state=state, start=start),
        )

    async def get_jobs(
        self,
        *,
        slug: str,
        start: int | Unset = UNSET,
    ) -> Response[m_get_company_jobs.CompanyJobsSuccess]:
        return await self._owner._request(
            m_get_company_jobs.CompanyJobsSuccess,
            m_get_company_jobs._get_kwargs(slug=slug, start=start),
        )

    async def search_by_domain(
        self,
        *,
        domain: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_companies_by_domain.CompanyDomainSearchSuccess]:
        return await self._owner._request(
            m_search_companies_by_domain.CompanyDomainSearchSuccess,
            m_search_companies_by_domain._get_kwargs(domain=domain, offset=offset),
        )

    async def search_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
        location: str | Unset = UNSET,
        industry: str | Unset = UNSET,
        company_size: str | Unset = UNSET,
        has_jobs: Literal["true"] | Unset = UNSET,
    ) -> Response[m_search_companies_by_keyword.CompanyDomainSearchSuccess]:
        return await self._owner._request(
            m_search_companies_by_keyword.CompanyDomainSearchSuccess,
            m_search_companies_by_keyword._get_kwargs(
                keywords=keywords,
                offset=offset,
                location=location,
                industry=industry,
                company_size=company_size,
                has_jobs=has_jobs,
            ),
        )

    async def get_details_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_company_details_by_url.CompanySuccess]:
        return await self._owner._request(
            m_get_company_details_by_url.CompanySuccess,
            m_get_company_details_by_url._get_kwargs(url_query=url),
        )

    async def get_details_by_slug(
        self,
        *,
        slug: str,
    ) -> Response[m_get_company_details_by_slug.CompanySuccess]:
        return await self._owner._request(
            m_get_company_details_by_slug.CompanySuccess,
            m_get_company_details_by_slug._get_kwargs(slug=slug),
        )

    async def get_details_by_id(
        self,
        *,
        public_id: str,
    ) -> Response[m_get_company_details_by_id.CompanySuccess]:
        return await self._owner._request(
            m_get_company_details_by_id.CompanySuccess,
            m_get_company_details_by_id._get_kwargs(public_id=public_id),
        )

    async def get_similar_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_similar_companies_by_url.SimilarCompaniesSuccess]:
        return await self._owner._request(
            m_get_similar_companies_by_url.SimilarCompaniesSuccess,
            m_get_similar_companies_by_url._get_kwargs(url_query=url),
        )

    async def get_similar_by_slug(
        self,
        *,
        slug: str,
    ) -> Response[m_get_similar_companies_by_slug.SimilarCompaniesSuccess]:
        return await self._owner._request(
            m_get_similar_companies_by_slug.SimilarCompaniesSuccess,
            m_get_similar_companies_by_slug._get_kwargs(slug=slug),
        )


class AsyncSchools:
    def __init__(self, owner: AsyncTransport):
        self._owner = owner

    async def search_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_schools_by_keyword.LinkedInV2SchoolSearchSuccess]:
        return await self._owner._request(
            m_search_schools_by_keyword.LinkedInV2SchoolSearchSuccess,
            m_search_schools_by_keyword._get_kwargs(keywords=keywords, offset=offset),
        )


class AsyncSearch:
    def __init__(self, owner: AsyncTransport):
        self._owner = owner

    async def search_all_results_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_all_results_by_keyword.KeywordSearchSuccess]:
        return await self._owner._request(
            m_search_all_results_by_keyword.KeywordSearchSuccess,
            m_search_all_results_by_keyword._get_kwargs(
                keywords=keywords, offset=offset
            ),
        )

    async def search_posts_by_hashtag(
        self,
        *,
        hashtag: str,
        offset: int | Unset = UNSET,
    ) -> Response[m_search_posts_by_hashtag.HashtagPostsSearchSuccess]:
        return await self._owner._request(
            m_search_posts_by_hashtag.HashtagPostsSearchSuccess,
            m_search_posts_by_hashtag._get_kwargs(hashtag=hashtag, offset=offset),
        )

    async def search_posts_by_keyword(
        self,
        *,
        keywords: str,
        offset: int | Unset = UNSET,
        sort: m_search_posts_by_keyword.SearchPostsByKeywordSort | Unset = UNSET,
        posted_within: m_search_posts_by_keyword.SearchPostsByKeywordPostedWithin
        | Unset = UNSET,
        content_type: m_search_posts_by_keyword.SearchPostsByKeywordContentType
        | Unset = UNSET,
    ) -> Response[m_search_posts_by_keyword.LinkedInV2SearchPostsSuccess]:
        return await self._owner._request(
            m_search_posts_by_keyword.LinkedInV2SearchPostsSuccess,
            m_search_posts_by_keyword._get_kwargs(
                keywords=keywords,
                offset=offset,
                sort=sort,
                posted_within=posted_within,
                content_type=content_type,
            ),
        )

    async def search_locations_by_keyword(
        self,
        *,
        keywords: str,
    ) -> Response[m_search_locations_by_keyword.LinkedInV2LocationSearchSuccess]:
        return await self._owner._request(
            m_search_locations_by_keyword.LinkedInV2LocationSearchSuccess,
            m_search_locations_by_keyword._get_kwargs(keywords=keywords),
        )

    async def search_industries_by_keyword(
        self,
        *,
        query: str,
    ) -> Response[m_search_industries_by_keyword.IndustrySearchSuccess]:
        return await self._owner._request(
            m_search_industries_by_keyword.IndustrySearchSuccess,
            m_search_industries_by_keyword._get_kwargs(query=query),
        )

    async def search_service_categories(
        self,
        *,
        query: str | Unset = UNSET,
    ) -> Response[m_search_service_categories.LinkedInV2ServiceCategorySearchSuccess]:
        return await self._owner._request(
            m_search_service_categories.LinkedInV2ServiceCategorySearchSuccess,
            m_search_service_categories._get_kwargs(query=query),
        )

    async def get_typeahead(
        self,
        *,
        query: str,
    ) -> Response[m_get_search_typeahead.LinkedInV2SearchTypeaheadSuccess]:
        return await self._owner._request(
            m_get_search_typeahead.LinkedInV2SearchTypeaheadSuccess,
            m_get_search_typeahead._get_kwargs(query=query),
        )


class AsyncJobs:
    def __init__(self, owner: AsyncTransport):
        self._owner = owner

    async def search(
        self,
        *,
        keywords: str,
        start: int | Unset = UNSET,
        location: str | Unset = UNSET,
        company_slug: str | Unset = UNSET,
        experience: m_search_jobs.SearchJobsExperience | Unset = UNSET,
        sort: m_search_jobs.SearchJobsSort | Unset = UNSET,
        time_posted: m_search_jobs.SearchJobsTimePosted | Unset = UNSET,
    ) -> Response[m_search_jobs.JobSearchSuccess]:
        return await self._owner._request(
            m_search_jobs.JobSearchSuccess,
            m_search_jobs._get_kwargs(
                keywords=keywords,
                start=start,
                location=location,
                company_slug=company_slug,
                experience=experience,
                sort=sort,
                time_posted=time_posted,
            ),
        )

    async def get_details(
        self,
        *,
        url: str,
    ) -> Response[m_get_job_details.JobDetailsSuccess]:
        return await self._owner._request(
            m_get_job_details.JobDetailsSuccess,
            m_get_job_details._get_kwargs(url_query=url),
        )


class AsyncPosts:
    def __init__(self, owner: AsyncTransport):
        self._owner = owner

    async def get_by_url(
        self,
        *,
        url: str,
    ) -> Response[m_get_post_by_url.LinkedInV2PostSuccess]:
        return await self._owner._request(
            m_get_post_by_url.LinkedInV2PostSuccess,
            m_get_post_by_url._get_kwargs(url_query=url),
        )

    async def get_by_slug(
        self,
        *,
        slug: str,
    ) -> Response[m_get_post_by_slug.LinkedInV2PostSuccess]:
        return await self._owner._request(
            m_get_post_by_slug.LinkedInV2PostSuccess,
            m_get_post_by_slug._get_kwargs(slug=slug),
        )

    async def get_comments_by_url(
        self,
        *,
        url: str,
        sort_order: m_get_post_comments_by_url.GetPostCommentsByUrlSortOrder
        | Unset = UNSET,
    ) -> Response[m_get_post_comments_by_url.LinkedInV2PostCommentsSuccess]:
        return await self._owner._request(
            m_get_post_comments_by_url.LinkedInV2PostCommentsSuccess,
            m_get_post_comments_by_url._get_kwargs(
                url_query=url, sort_order=sort_order
            ),
        )

    async def get_comments_by_slug(
        self,
        *,
        slug: str,
        sort_order: m_get_post_comments_by_slug.GetPostCommentsBySlugSortOrder
        | Unset = UNSET,
    ) -> Response[m_get_post_comments_by_slug.LinkedInV2PostCommentsSuccess]:
        return await self._owner._request(
            m_get_post_comments_by_slug.LinkedInV2PostCommentsSuccess,
            m_get_post_comments_by_slug._get_kwargs(slug=slug, sort_order=sort_order),
        )

    async def get_reactions_by_url(
        self,
        *,
        url: str,
        reaction_type: m_get_post_reactions_by_url.GetPostReactionsByUrlReactionType,
    ) -> Response[m_get_post_reactions_by_url.LinkedInV2PostReactionsSuccess]:
        return await self._owner._request(
            m_get_post_reactions_by_url.LinkedInV2PostReactionsSuccess,
            m_get_post_reactions_by_url._get_kwargs(
                url_query=url, reaction_type=reaction_type
            ),
        )

    async def get_reactions_by_slug(
        self,
        *,
        slug: str,
        reaction_type: m_get_post_reactions_by_slug.GetPostReactionsBySlugReactionType,
    ) -> Response[m_get_post_reactions_by_slug.LinkedInV2PostReactionsSuccess]:
        return await self._owner._request(
            m_get_post_reactions_by_slug.LinkedInV2PostReactionsSuccess,
            m_get_post_reactions_by_slug._get_kwargs(
                slug=slug, reaction_type=reaction_type
            ),
        )
