from enum import StrEnum


class LinkedInV2PublicAttributeName(StrEnum):
    AFFILIATION = "affiliation"
    ASSOCIATION = "association"
    CAUSE = "cause"
    CERTIFICATIONNAME = "certificationName"
    COMPANYLOGOURL = "companyLogoUrl"
    COMPANYSLUG = "companySlug"
    COURSENAME = "courseName"
    CREDENTIALID = "credentialId"
    DATE = "date"
    DESCRIPTION = "description"
    DURATION = "duration"
    ENDORSEMENTCOUNT = "endorsementCount"
    EXPIRATIONDATE = "expirationDate"
    FIRSTNAME = "firstName"
    FOLLOWERCOUNT = "followerCount"
    HEADLINE = "headline"
    ID = "id"
    INDUSTRY = "industry"
    INSIGHT = "insight"
    ISSUEDDATE = "issuedDate"
    ISSUERNAME = "issuerName"
    LANGUAGE = "language"
    LASTNAME = "lastName"
    LOCATION = "location"
    NAME = "name"
    ORGANIZATIONNAME = "organizationName"
    PROFICIENCY = "proficiency"
    PROFILEPICTUREURL = "profilePictureUrl"
    PROGRAM = "program"
    REACTIONTYPE = "reactionType"
    ROLE = "role"
    SCHOOLNAME = "schoolName"
    SKILLNAME = "skillName"
    STATUS = "status"
    SUBTITLE = "subtitle"
    SUMMARY = "summary"
    TEXT = "text"
    TITLE = "title"
    TYPE = "type"
    USERNAME = "username"

    def __str__(self) -> str:
        return str(self.value)
