// Generated by scripts/generate.mjs. Do not edit.
import { Transport, type ClientOptions, type RequestOptions } from './runtime.js';
import type { operations } from './schema.js';
export { APIError, TransportError, DecodeError } from './runtime.js';
export type { APIResponse, ClientOptions, RequestOptions } from './runtime.js';
export type { paths, components, operations } from './schema.js';

export class Profiles {
  constructor(private readonly transport: Transport) {}
  getPosts(params: operations['getProfilePosts']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfilePosts']['responses'][200]['content']['application/json']>('/v1/profiles/posts', params, options);
  }
  getComments(params: operations['getProfileComments']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileComments']['responses'][200]['content']['application/json']>('/v1/profiles/comments', params, options);
  }
  getReactions(params: operations['getProfileReactions']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileReactions']['responses'][200]['content']['application/json']>('/v1/profiles/reactions', params, options);
  }
  getSimilar(params: operations['getSimilarProfiles']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getSimilarProfiles']['responses'][200]['content']['application/json']>('/v1/profiles/similar', params, options);
  }
  searchByKeyword(params: operations['searchPeopleByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchPeopleByKeyword']['responses'][200]['content']['application/json']>('/v1/profiles/search', params, options);
  }
  getDetailsByUrl(params: operations['getProfileDetailsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileDetailsByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/details/by-url', params, options);
  }
  getDetailsByUsername(params: operations['getProfileDetailsByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileDetailsByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/details/by-username', params, options);
  }
  getDetailsById(params: operations['getProfileDetailsById']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileDetailsById']['responses'][200]['content']['application/json']>('/v1/profiles/details/by-id', params, options);
  }
  getContactByUrl(params: operations['getProfileContactByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileContactByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/contact/by-url', params, options);
  }
  getContactByUsername(params: operations['getProfileContactByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileContactByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/contact/by-username', params, options);
  }
  getFullExperienceByUrl(params: operations['getProfileFullExperienceByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileFullExperienceByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/experience/by-url', params, options);
  }
  getFullExperienceByUsername(params: operations['getProfileFullExperienceByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileFullExperienceByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/experience/by-username', params, options);
  }
  getEducationByUrl(params: operations['getProfileEducationByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileEducationByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/education/by-url', params, options);
  }
  getEducationByUsername(params: operations['getProfileEducationByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileEducationByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/education/by-username', params, options);
  }
  getSkillsByUrl(params: operations['getProfileSkillsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileSkillsByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/skills/by-url', params, options);
  }
  getSkillsByUsername(params: operations['getProfileSkillsByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileSkillsByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/skills/by-username', params, options);
  }
  getCertificationsByUrl(params: operations['getProfileCertificationsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCertificationsByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/certifications/by-url', params, options);
  }
  getCertificationsByUsername(params: operations['getProfileCertificationsByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCertificationsByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/certifications/by-username', params, options);
  }
  getCoursesByUrl(params: operations['getProfileCoursesByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCoursesByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/courses/by-url', params, options);
  }
  getCoursesByUsername(params: operations['getProfileCoursesByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCoursesByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/courses/by-username', params, options);
  }
  getCompanyInterestsByUrl(params: operations['getProfileCompanyInterestsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCompanyInterestsByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/company-interests/by-url', params, options);
  }
  getCompanyInterestsByUsername(params: operations['getProfileCompanyInterestsByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCompanyInterestsByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/company-interests/by-username', params, options);
  }
  getCompanyInterestsById(params: operations['getProfileCompanyInterestsById']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileCompanyInterestsById']['responses'][200]['content']['application/json']>('/v1/profiles/company-interests/by-id', params, options);
  }
  getVolunteerExperienceByUrl(params: operations['getProfileVolunteerExperienceByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileVolunteerExperienceByUrl']['responses'][200]['content']['application/json']>('/v1/profiles/volunteer-experience/by-url', params, options);
  }
  getVolunteerExperienceByUsername(params: operations['getProfileVolunteerExperienceByUsername']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getProfileVolunteerExperienceByUsername']['responses'][200]['content']['application/json']>('/v1/profiles/volunteer-experience/by-username', params, options);
  }
}
export class Companies {
  constructor(private readonly transport: Transport) {}
  getPosts(params: operations['getCompanyPosts']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyPosts']['responses'][200]['content']['application/json']>('/v1/companies/posts', params, options);
  }
  getPeople(params: operations['getCompanyPeople']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyPeople']['responses'][200]['content']['application/json']>('/v1/companies/people', params, options);
  }
  getProducts(params: operations['getCompanyProducts']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyProducts']['responses'][200]['content']['application/json']>('/v1/companies/products', params, options);
  }
  getJobs(params: operations['getCompanyJobs']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyJobs']['responses'][200]['content']['application/json']>('/v1/companies/jobs', params, options);
  }
  searchByDomain(params: operations['searchCompaniesByDomain']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchCompaniesByDomain']['responses'][200]['content']['application/json']>('/v1/companies/by-domain', params, options);
  }
  searchByKeyword(params: operations['searchCompaniesByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchCompaniesByKeyword']['responses'][200]['content']['application/json']>('/v1/companies/search', params, options);
  }
  getDetailsByUrl(params: operations['getCompanyDetailsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyDetailsByUrl']['responses'][200]['content']['application/json']>('/v1/companies/details/by-url', params, options);
  }
  getDetailsBySlug(params: operations['getCompanyDetailsBySlug']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyDetailsBySlug']['responses'][200]['content']['application/json']>('/v1/companies/details/by-slug', params, options);
  }
  getDetailsById(params: operations['getCompanyDetailsById']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getCompanyDetailsById']['responses'][200]['content']['application/json']>('/v1/companies/details/by-id', params, options);
  }
  getSimilarByUrl(params: operations['getSimilarCompaniesByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getSimilarCompaniesByUrl']['responses'][200]['content']['application/json']>('/v1/companies/similar/by-url', params, options);
  }
  getSimilarBySlug(params: operations['getSimilarCompaniesBySlug']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getSimilarCompaniesBySlug']['responses'][200]['content']['application/json']>('/v1/companies/similar/by-slug', params, options);
  }
}
export class Schools {
  constructor(private readonly transport: Transport) {}
  searchByKeyword(params: operations['searchSchoolsByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchSchoolsByKeyword']['responses'][200]['content']['application/json']>('/v1/schools/search', params, options);
  }
}
export class Search {
  constructor(private readonly transport: Transport) {}
  searchAllResultsByKeyword(params: operations['searchAllResultsByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchAllResultsByKeyword']['responses'][200]['content']['application/json']>('/v1/search', params, options);
  }
  searchPostsByHashtag(params: operations['searchPostsByHashtag']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchPostsByHashtag']['responses'][200]['content']['application/json']>('/v1/search/posts/by-hashtag', params, options);
  }
  searchPostsByKeyword(params: operations['searchPostsByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchPostsByKeyword']['responses'][200]['content']['application/json']>('/v1/search/posts', params, options);
  }
  searchLocationsByKeyword(params: operations['searchLocationsByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchLocationsByKeyword']['responses'][200]['content']['application/json']>('/v1/search/locations', params, options);
  }
  searchIndustriesByKeyword(params: operations['searchIndustriesByKeyword']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchIndustriesByKeyword']['responses'][200]['content']['application/json']>('/v1/search/industries', params, options);
  }
  searchServiceCategories(params: operations['searchServiceCategories']['parameters']['query'] = {}, options?: RequestOptions) {
    return this.transport.request<operations['searchServiceCategories']['responses'][200]['content']['application/json']>('/v1/search/service-categories', params, options);
  }
  getTypeahead(params: operations['getSearchTypeahead']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getSearchTypeahead']['responses'][200]['content']['application/json']>('/v1/search/typeahead', params, options);
  }
}
export class Jobs {
  constructor(private readonly transport: Transport) {}
  search(params: operations['searchJobs']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['searchJobs']['responses'][200]['content']['application/json']>('/v1/jobs/search', params, options);
  }
  getDetails(params: operations['getJobDetails']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getJobDetails']['responses'][200]['content']['application/json']>('/v1/jobs/details', params, options);
  }
}
export class Posts {
  constructor(private readonly transport: Transport) {}
  getByUrl(params: operations['getPostByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getPostByUrl']['responses'][200]['content']['application/json']>('/v1/posts/details/by-url', params, options);
  }
  getBySlug(params: operations['getPostBySlug']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getPostBySlug']['responses'][200]['content']['application/json']>('/v1/posts/details/by-slug', params, options);
  }
  getCommentsByUrl(params: operations['getPostCommentsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getPostCommentsByUrl']['responses'][200]['content']['application/json']>('/v1/posts/comments/by-url', params, options);
  }
  getCommentsBySlug(params: operations['getPostCommentsBySlug']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getPostCommentsBySlug']['responses'][200]['content']['application/json']>('/v1/posts/comments/by-slug', params, options);
  }
  getReactionsByUrl(params: operations['getPostReactionsByUrl']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getPostReactionsByUrl']['responses'][200]['content']['application/json']>('/v1/posts/reactions/by-url', params, options);
  }
  getReactionsBySlug(params: operations['getPostReactionsBySlug']['parameters']['query'], options?: RequestOptions) {
    return this.transport.request<operations['getPostReactionsBySlug']['responses'][200]['content']['application/json']>('/v1/posts/reactions/by-slug', params, options);
  }
}
export class EnvoAPI {
  readonly profiles: Profiles;
  readonly companies: Companies;
  readonly schools: Schools;
  readonly search: Search;
  readonly jobs: Jobs;
  readonly posts: Posts;
  constructor(options: ClientOptions = {}) {
    const transport = new Transport(options);
    this.profiles = new Profiles(transport);
    this.companies = new Companies(transport);
    this.schools = new Schools(transport);
    this.search = new Search(transport);
    this.jobs = new Jobs(transport);
    this.posts = new Posts(transport);
  }
}
