// Code generated by scripts/generate.mjs. DO NOT EDIT.
package envoapi

import (
	"context"
	"github.com/envoapi-official/envoapi-sdks/go/api"
	"time"
)

type Client struct {
	raw       *api.Client
	timeout   time.Duration
	Profiles  *ProfilesService
	Companies *CompaniesService
	Schools   *SchoolsService
	Search    *SearchService
	Jobs      *JobsService
	Posts     *PostsService
}

func (c *Client) initResources() {
	c.Profiles = &ProfilesService{client: c}
	c.Companies = &CompaniesService{client: c}
	c.Schools = &SchoolsService{client: c}
	c.Search = &SearchService{client: c}
	c.Jobs = &JobsService{client: c}
	c.Posts = &PostsService{client: c}
}

type ProfilesService struct{ client *Client }
type GetProfilePostsParams = api.GetProfilePostsParams

func (s *ProfilesService) GetPosts(ctx context.Context, params GetProfilePostsParams) (*Response[api.ProfilePostsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfilePosts(ctx, &params)
	return decode[api.ProfilePostsSuccess](response, err)
}

type GetProfileCommentsParams = api.GetProfileCommentsParams

func (s *ProfilesService) GetComments(ctx context.Context, params GetProfileCommentsParams) (*Response[api.ProfileCommentsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileComments(ctx, &params)
	return decode[api.ProfileCommentsSuccess](response, err)
}

type GetProfileReactionsParams = api.GetProfileReactionsParams

func (s *ProfilesService) GetReactions(ctx context.Context, params GetProfileReactionsParams) (*Response[api.ProfileReactionsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileReactions(ctx, &params)
	return decode[api.ProfileReactionsSuccess](response, err)
}

type GetSimilarProfilesParams = api.GetSimilarProfilesParams

func (s *ProfilesService) GetSimilar(ctx context.Context, params GetSimilarProfilesParams) (*Response[api.SimilarProfilesSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetSimilarProfiles(ctx, &params)
	return decode[api.SimilarProfilesSuccess](response, err)
}

type SearchPeopleByKeywordParams = api.SearchPeopleByKeywordParams

func (s *ProfilesService) SearchByKeyword(ctx context.Context, params SearchPeopleByKeywordParams) (*Response[api.PeopleKeywordSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchPeopleByKeyword(ctx, &params)
	return decode[api.PeopleKeywordSearchSuccess](response, err)
}

type GetProfileDetailsByUrlParams = api.GetProfileDetailsByUrlParams

func (s *ProfilesService) GetDetailsByUrl(ctx context.Context, params GetProfileDetailsByUrlParams) (*Response[api.ProfileSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileDetailsByUrl(ctx, &params)
	return decode[api.ProfileSuccess](response, err)
}

type GetProfileDetailsByUsernameParams = api.GetProfileDetailsByUsernameParams

func (s *ProfilesService) GetDetailsByUsername(ctx context.Context, params GetProfileDetailsByUsernameParams) (*Response[api.ProfileSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileDetailsByUsername(ctx, &params)
	return decode[api.ProfileSuccess](response, err)
}

type GetProfileDetailsByIdParams = api.GetProfileDetailsByIdParams

func (s *ProfilesService) GetDetailsById(ctx context.Context, params GetProfileDetailsByIdParams) (*Response[api.ProfileSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileDetailsById(ctx, &params)
	return decode[api.ProfileSuccess](response, err)
}

type GetProfileContactByUrlParams = api.GetProfileContactByUrlParams

func (s *ProfilesService) GetContactByUrl(ctx context.Context, params GetProfileContactByUrlParams) (*Response[api.ProfileContactSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileContactByUrl(ctx, &params)
	return decode[api.ProfileContactSuccess](response, err)
}

type GetProfileContactByUsernameParams = api.GetProfileContactByUsernameParams

func (s *ProfilesService) GetContactByUsername(ctx context.Context, params GetProfileContactByUsernameParams) (*Response[api.ProfileContactSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileContactByUsername(ctx, &params)
	return decode[api.ProfileContactSuccess](response, err)
}

type GetProfileFullExperienceByUrlParams = api.GetProfileFullExperienceByUrlParams

func (s *ProfilesService) GetFullExperienceByUrl(ctx context.Context, params GetProfileFullExperienceByUrlParams) (*Response[api.ProfileExperienceSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileFullExperienceByUrl(ctx, &params)
	return decode[api.ProfileExperienceSuccess](response, err)
}

type GetProfileFullExperienceByUsernameParams = api.GetProfileFullExperienceByUsernameParams

func (s *ProfilesService) GetFullExperienceByUsername(ctx context.Context, params GetProfileFullExperienceByUsernameParams) (*Response[api.ProfileExperienceSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileFullExperienceByUsername(ctx, &params)
	return decode[api.ProfileExperienceSuccess](response, err)
}

type GetProfileEducationByUrlParams = api.GetProfileEducationByUrlParams

func (s *ProfilesService) GetEducationByUrl(ctx context.Context, params GetProfileEducationByUrlParams) (*Response[api.ProfileEducationSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileEducationByUrl(ctx, &params)
	return decode[api.ProfileEducationSuccess](response, err)
}

type GetProfileEducationByUsernameParams = api.GetProfileEducationByUsernameParams

func (s *ProfilesService) GetEducationByUsername(ctx context.Context, params GetProfileEducationByUsernameParams) (*Response[api.ProfileEducationSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileEducationByUsername(ctx, &params)
	return decode[api.ProfileEducationSuccess](response, err)
}

type GetProfileSkillsByUrlParams = api.GetProfileSkillsByUrlParams

func (s *ProfilesService) GetSkillsByUrl(ctx context.Context, params GetProfileSkillsByUrlParams) (*Response[api.ProfileSkillsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileSkillsByUrl(ctx, &params)
	return decode[api.ProfileSkillsSuccess](response, err)
}

type GetProfileSkillsByUsernameParams = api.GetProfileSkillsByUsernameParams

func (s *ProfilesService) GetSkillsByUsername(ctx context.Context, params GetProfileSkillsByUsernameParams) (*Response[api.ProfileSkillsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileSkillsByUsername(ctx, &params)
	return decode[api.ProfileSkillsSuccess](response, err)
}

type GetProfileCertificationsByUrlParams = api.GetProfileCertificationsByUrlParams

func (s *ProfilesService) GetCertificationsByUrl(ctx context.Context, params GetProfileCertificationsByUrlParams) (*Response[api.ProfileCertificationsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCertificationsByUrl(ctx, &params)
	return decode[api.ProfileCertificationsSuccess](response, err)
}

type GetProfileCertificationsByUsernameParams = api.GetProfileCertificationsByUsernameParams

func (s *ProfilesService) GetCertificationsByUsername(ctx context.Context, params GetProfileCertificationsByUsernameParams) (*Response[api.ProfileCertificationsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCertificationsByUsername(ctx, &params)
	return decode[api.ProfileCertificationsSuccess](response, err)
}

type GetProfileCoursesByUrlParams = api.GetProfileCoursesByUrlParams

func (s *ProfilesService) GetCoursesByUrl(ctx context.Context, params GetProfileCoursesByUrlParams) (*Response[api.ProfileCoursesSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCoursesByUrl(ctx, &params)
	return decode[api.ProfileCoursesSuccess](response, err)
}

type GetProfileCoursesByUsernameParams = api.GetProfileCoursesByUsernameParams

func (s *ProfilesService) GetCoursesByUsername(ctx context.Context, params GetProfileCoursesByUsernameParams) (*Response[api.ProfileCoursesSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCoursesByUsername(ctx, &params)
	return decode[api.ProfileCoursesSuccess](response, err)
}

type GetProfileCompanyInterestsByUrlParams = api.GetProfileCompanyInterestsByUrlParams

func (s *ProfilesService) GetCompanyInterestsByUrl(ctx context.Context, params GetProfileCompanyInterestsByUrlParams) (*Response[api.ProfileCompanyInterestsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCompanyInterestsByUrl(ctx, &params)
	return decode[api.ProfileCompanyInterestsSuccess](response, err)
}

type GetProfileCompanyInterestsByUsernameParams = api.GetProfileCompanyInterestsByUsernameParams

func (s *ProfilesService) GetCompanyInterestsByUsername(ctx context.Context, params GetProfileCompanyInterestsByUsernameParams) (*Response[api.ProfileCompanyInterestsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCompanyInterestsByUsername(ctx, &params)
	return decode[api.ProfileCompanyInterestsSuccess](response, err)
}

type GetProfileCompanyInterestsByIdParams = api.GetProfileCompanyInterestsByIdParams

func (s *ProfilesService) GetCompanyInterestsById(ctx context.Context, params GetProfileCompanyInterestsByIdParams) (*Response[api.ProfileCompanyInterestsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileCompanyInterestsById(ctx, &params)
	return decode[api.ProfileCompanyInterestsSuccess](response, err)
}

type GetProfileVolunteerExperienceByUrlParams = api.GetProfileVolunteerExperienceByUrlParams

func (s *ProfilesService) GetVolunteerExperienceByUrl(ctx context.Context, params GetProfileVolunteerExperienceByUrlParams) (*Response[api.ProfileVolunteerExperienceSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileVolunteerExperienceByUrl(ctx, &params)
	return decode[api.ProfileVolunteerExperienceSuccess](response, err)
}

type GetProfileVolunteerExperienceByUsernameParams = api.GetProfileVolunteerExperienceByUsernameParams

func (s *ProfilesService) GetVolunteerExperienceByUsername(ctx context.Context, params GetProfileVolunteerExperienceByUsernameParams) (*Response[api.ProfileVolunteerExperienceSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetProfileVolunteerExperienceByUsername(ctx, &params)
	return decode[api.ProfileVolunteerExperienceSuccess](response, err)
}

type CompaniesService struct{ client *Client }
type GetCompanyPostsParams = api.GetCompanyPostsParams

func (s *CompaniesService) GetPosts(ctx context.Context, params GetCompanyPostsParams) (*Response[api.CompanyPostsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyPosts(ctx, &params)
	return decode[api.CompanyPostsSuccess](response, err)
}

type GetCompanyPeopleParams = api.GetCompanyPeopleParams

func (s *CompaniesService) GetPeople(ctx context.Context, params GetCompanyPeopleParams) (*Response[api.CompanyPeopleSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyPeople(ctx, &params)
	return decode[api.CompanyPeopleSuccess](response, err)
}

type GetCompanyProductsParams = api.GetCompanyProductsParams

func (s *CompaniesService) GetProducts(ctx context.Context, params GetCompanyProductsParams) (*Response[api.LinkedInV2CompanyProductsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyProducts(ctx, &params)
	return decode[api.LinkedInV2CompanyProductsSuccess](response, err)
}

type GetCompanyJobsParams = api.GetCompanyJobsParams

func (s *CompaniesService) GetJobs(ctx context.Context, params GetCompanyJobsParams) (*Response[api.CompanyJobsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyJobs(ctx, &params)
	return decode[api.CompanyJobsSuccess](response, err)
}

type SearchCompaniesByDomainParams = api.SearchCompaniesByDomainParams

func (s *CompaniesService) SearchByDomain(ctx context.Context, params SearchCompaniesByDomainParams) (*Response[api.CompanyDomainSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchCompaniesByDomain(ctx, &params)
	return decode[api.CompanyDomainSearchSuccess](response, err)
}

type SearchCompaniesByKeywordParams = api.SearchCompaniesByKeywordParams

func (s *CompaniesService) SearchByKeyword(ctx context.Context, params SearchCompaniesByKeywordParams) (*Response[api.CompanyDomainSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchCompaniesByKeyword(ctx, &params)
	return decode[api.CompanyDomainSearchSuccess](response, err)
}

type GetCompanyDetailsByUrlParams = api.GetCompanyDetailsByUrlParams

func (s *CompaniesService) GetDetailsByUrl(ctx context.Context, params GetCompanyDetailsByUrlParams) (*Response[api.CompanySuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyDetailsByUrl(ctx, &params)
	return decode[api.CompanySuccess](response, err)
}

type GetCompanyDetailsBySlugParams = api.GetCompanyDetailsBySlugParams

func (s *CompaniesService) GetDetailsBySlug(ctx context.Context, params GetCompanyDetailsBySlugParams) (*Response[api.CompanySuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyDetailsBySlug(ctx, &params)
	return decode[api.CompanySuccess](response, err)
}

type GetCompanyDetailsByIdParams = api.GetCompanyDetailsByIdParams

func (s *CompaniesService) GetDetailsById(ctx context.Context, params GetCompanyDetailsByIdParams) (*Response[api.CompanySuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetCompanyDetailsById(ctx, &params)
	return decode[api.CompanySuccess](response, err)
}

type GetSimilarCompaniesByUrlParams = api.GetSimilarCompaniesByUrlParams

func (s *CompaniesService) GetSimilarByUrl(ctx context.Context, params GetSimilarCompaniesByUrlParams) (*Response[api.SimilarCompaniesSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetSimilarCompaniesByUrl(ctx, &params)
	return decode[api.SimilarCompaniesSuccess](response, err)
}

type GetSimilarCompaniesBySlugParams = api.GetSimilarCompaniesBySlugParams

func (s *CompaniesService) GetSimilarBySlug(ctx context.Context, params GetSimilarCompaniesBySlugParams) (*Response[api.SimilarCompaniesSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetSimilarCompaniesBySlug(ctx, &params)
	return decode[api.SimilarCompaniesSuccess](response, err)
}

type SchoolsService struct{ client *Client }
type SearchSchoolsByKeywordParams = api.SearchSchoolsByKeywordParams

func (s *SchoolsService) SearchByKeyword(ctx context.Context, params SearchSchoolsByKeywordParams) (*Response[api.LinkedInV2SchoolSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchSchoolsByKeyword(ctx, &params)
	return decode[api.LinkedInV2SchoolSearchSuccess](response, err)
}

type SearchService struct{ client *Client }
type SearchAllResultsByKeywordParams = api.SearchAllResultsByKeywordParams

func (s *SearchService) SearchAllResultsByKeyword(ctx context.Context, params SearchAllResultsByKeywordParams) (*Response[api.KeywordSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchAllResultsByKeyword(ctx, &params)
	return decode[api.KeywordSearchSuccess](response, err)
}

type SearchPostsByHashtagParams = api.SearchPostsByHashtagParams

func (s *SearchService) SearchPostsByHashtag(ctx context.Context, params SearchPostsByHashtagParams) (*Response[api.HashtagPostsSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchPostsByHashtag(ctx, &params)
	return decode[api.HashtagPostsSearchSuccess](response, err)
}

type SearchPostsByKeywordParams = api.SearchPostsByKeywordParams

func (s *SearchService) SearchPostsByKeyword(ctx context.Context, params SearchPostsByKeywordParams) (*Response[api.LinkedInV2SearchPostsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchPostsByKeyword(ctx, &params)
	return decode[api.LinkedInV2SearchPostsSuccess](response, err)
}

type SearchLocationsByKeywordParams = api.SearchLocationsByKeywordParams

func (s *SearchService) SearchLocationsByKeyword(ctx context.Context, params SearchLocationsByKeywordParams) (*Response[api.LinkedInV2LocationSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchLocationsByKeyword(ctx, &params)
	return decode[api.LinkedInV2LocationSearchSuccess](response, err)
}

type SearchIndustriesByKeywordParams = api.SearchIndustriesByKeywordParams

func (s *SearchService) SearchIndustriesByKeyword(ctx context.Context, params SearchIndustriesByKeywordParams) (*Response[api.IndustrySearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchIndustriesByKeyword(ctx, &params)
	return decode[api.IndustrySearchSuccess](response, err)
}

type SearchServiceCategoriesParams = api.SearchServiceCategoriesParams

func (s *SearchService) SearchServiceCategories(ctx context.Context, params SearchServiceCategoriesParams) (*Response[api.LinkedInV2ServiceCategorySearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchServiceCategories(ctx, &params)
	return decode[api.LinkedInV2ServiceCategorySearchSuccess](response, err)
}

type GetSearchTypeaheadParams = api.GetSearchTypeaheadParams

func (s *SearchService) GetTypeahead(ctx context.Context, params GetSearchTypeaheadParams) (*Response[api.LinkedInV2SearchTypeaheadSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetSearchTypeahead(ctx, &params)
	return decode[api.LinkedInV2SearchTypeaheadSuccess](response, err)
}

type JobsService struct{ client *Client }
type SearchJobsParams = api.SearchJobsParams

func (s *JobsService) Search(ctx context.Context, params SearchJobsParams) (*Response[api.JobSearchSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.SearchJobs(ctx, &params)
	return decode[api.JobSearchSuccess](response, err)
}

type GetJobDetailsParams = api.GetJobDetailsParams

func (s *JobsService) GetDetails(ctx context.Context, params GetJobDetailsParams) (*Response[api.JobDetailsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetJobDetails(ctx, &params)
	return decode[api.JobDetailsSuccess](response, err)
}

type PostsService struct{ client *Client }
type GetPostByUrlParams = api.GetPostByUrlParams

func (s *PostsService) GetByUrl(ctx context.Context, params GetPostByUrlParams) (*Response[api.LinkedInV2PostSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetPostByUrl(ctx, &params)
	return decode[api.LinkedInV2PostSuccess](response, err)
}

type GetPostBySlugParams = api.GetPostBySlugParams

func (s *PostsService) GetBySlug(ctx context.Context, params GetPostBySlugParams) (*Response[api.LinkedInV2PostSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetPostBySlug(ctx, &params)
	return decode[api.LinkedInV2PostSuccess](response, err)
}

type GetPostCommentsByUrlParams = api.GetPostCommentsByUrlParams

func (s *PostsService) GetCommentsByUrl(ctx context.Context, params GetPostCommentsByUrlParams) (*Response[api.LinkedInV2PostCommentsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetPostCommentsByUrl(ctx, &params)
	return decode[api.LinkedInV2PostCommentsSuccess](response, err)
}

type GetPostCommentsBySlugParams = api.GetPostCommentsBySlugParams

func (s *PostsService) GetCommentsBySlug(ctx context.Context, params GetPostCommentsBySlugParams) (*Response[api.LinkedInV2PostCommentsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetPostCommentsBySlug(ctx, &params)
	return decode[api.LinkedInV2PostCommentsSuccess](response, err)
}

type GetPostReactionsByUrlParams = api.GetPostReactionsByUrlParams

func (s *PostsService) GetReactionsByUrl(ctx context.Context, params GetPostReactionsByUrlParams) (*Response[api.LinkedInV2PostReactionsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetPostReactionsByUrl(ctx, &params)
	return decode[api.LinkedInV2PostReactionsSuccess](response, err)
}

type GetPostReactionsBySlugParams = api.GetPostReactionsBySlugParams

func (s *PostsService) GetReactionsBySlug(ctx context.Context, params GetPostReactionsBySlugParams) (*Response[api.LinkedInV2PostReactionsSuccess], error) {
	ctx, cancel := context.WithTimeout(ctx, s.client.timeout)
	defer cancel()
	response, err := s.client.raw.GetPostReactionsBySlug(ctx, &params)
	return decode[api.LinkedInV2PostReactionsSuccess](response, err)
}
