import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import YAML from "yaml";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "envoapi-generate-"));
const env = {
  ...process.env,
  PATH: [
    path.join(root, ".venv/bin"),
    path.join(root, ".tools/go/bin"),
    process.env.PATH,
  ].join(path.delimiter),
};
const run = (cmd, args) => {
  const r = spawnSync(cmd, args, {
    cwd: root,
    env,
    encoding: "utf8",
    maxBuffer: 16 * 1024 * 1024,
  });
  if (r.status !== 0)
    throw new Error(
      `${cmd} failed: ${r.error ?? ""}\n${r.stdout}\n${r.stderr}`,
    );
  if (
    /Warning\(s\)|Skipping Integration|Errors? encountered/.test(
      r.stdout + r.stderr,
    )
  )
    throw new Error(r.stdout + r.stderr);
  return r.stdout;
};
const upper = (s) => s[0].toUpperCase() + s.slice(1);
const snake = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
const outputs = new Map();
const put = (name, value) => outputs.set(name, value);
const spec = YAML.parse(
  fs.readFileSync(path.join(root, "openapi/public-v1.yaml"), "utf8"),
);
const manifest = [];
for (const [route, item] of Object.entries(spec.paths))
  for (const [verb, op] of Object.entries(item)) {
    if (!op.operationId) continue;
    if (verb !== "get")
      throw new Error(`Unsupported operation method: ${verb} ${route}`);
    const resource = route.split("/")[2];
    const replacements = {
      profiles: /Profile(s)?|People/,
      companies: /Company|Companies/,
      schools: /Schools?/,
      jobs: /Jobs?/,
      posts: /Posts?/,
    };
    let name = op.operationId;
    if (replacements[resource]) name = name.replace(replacements[resource], "");
    // Preserve useful search operation names, but avoid repeating the resource itself.
    if (resource === "search")
      name = name.replace("SearchTypeahead", "Typeahead");
    manifest.push({
      operationId: op.operationId,
      method: verb.toUpperCase(),
      path: route,
      resource,
      typescript: name,
      python: snake(name),
      go: upper(name),
      response: op.responses["200"].content["application/json"].schema.$ref
        .split("/")
        .at(-1),
    });
  }
for (const lang of ["typescript", "python", "go"]) {
  const names = manifest.map((m) => m.resource + "." + m[lang]);
  if (new Set(names).size !== names.length)
    throw new Error(`Duplicate ${lang} method`);
}
try {
  run("pnpm", [
    "exec",
    "openapi-typescript",
    "openapi/public-v1.yaml",
    "-o",
    path.join(tmp, "schema.ts"),
  ]);
  put(
    "typescript/src/schema.ts",
    fs.readFileSync(path.join(tmp, "schema.ts"), "utf8"),
  );
  run("openapi-python-client", [
    "generate",
    "--fail-on-warning",
    "--path",
    "openapi/public-v1.yaml",
    "--config",
    "python/generator.yaml",
    "--custom-template-path",
    "python/templates",
    "--output-path",
    path.join(tmp, "python"),
  ]);
  const walk = (dir, prefix = "") => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const relative = path.join(prefix, entry.name),
        full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full, relative);
      else if (!relative.includes("__pycache__"))
        put(
          "python/envoapi/_generated/" + relative,
          fs.readFileSync(full, "utf8"),
        );
    }
  };
  walk(path.join(tmp, "python/envoapi"));
  const goSource = run("go", [
    "run",
    "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0",
    "--config",
    "go/oapi-codegen.yaml",
    "openapi/public-v1.yaml",
  ]);
  put("go/api/generated.go", goSource);
  put("openapi/operations.json", JSON.stringify(manifest, null, 2) + "\n");
  const groups = [...new Set(manifest.map((m) => m.resource))];

  let ts = `// Generated by scripts/generate.mjs. Do not edit.\nimport { Transport, type ClientOptions, type RequestOptions } from './runtime.js';\nimport type { operations } from './schema.js';\nexport { APIError, TransportError, DecodeError } from './runtime.js';\nexport type { APIResponse, ClientOptions, RequestOptions } from './runtime.js';\nexport type { paths, components, operations } from './schema.js';\n\n`;
  for (const group of groups) {
    ts += `export class ${upper(group)} {\n  constructor(private readonly transport: Transport) {}\n`;
    for (const m of manifest.filter((m) => m.resource === group)) {
      const optional = !spec.paths[m.path].get.parameters.some(
        (p) => p.required,
      );
      ts += `  ${m.typescript}(params: operations['${m.operationId}']['parameters']['query']${optional ? " = {}" : ""}, options?: RequestOptions) {\n    return this.transport.request<operations['${m.operationId}']['responses'][200]['content']['application/json']>('${m.path}', params, options);\n  }\n`;
    }
    ts += "}\n";
  }
  ts +=
    "export class EnvoAPI {\n" +
    groups.map((g) => `  readonly ${g}: ${upper(g)};`).join("\n") +
    "\n  constructor(options: ClientOptions = {}) {\n    const transport = new Transport(options);\n" +
    groups
      .map((g) => `    this.${g} = new ${upper(g)}(transport);`)
      .join("\n") +
    "\n  }\n}\n";
  put("typescript/src/index.ts", ts);

  let py =
    "# Generated by scripts/generate.mjs. Do not edit.\nfrom __future__ import annotations\nfrom typing import Literal\nfrom .runtime import Response, SyncTransport, AsyncTransport\nfrom ._generated.types import UNSET, Unset\n";
  for (const m of manifest)
    py += `from ._generated.api.default import ${snake(m.operationId)} as m_${snake(m.operationId)}\n`;
  for (const async of [false, true])
    for (const group of groups) {
      py += `\nclass ${async ? "Async" : ""}${upper(group)}:\n    def __init__(self, owner: ${async ? "Async" : "Sync"}Transport):\n        self._owner = owner\n`;
      for (const m of manifest.filter((m) => m.resource === group)) {
        const mod = snake(m.operationId);
        const source = outputs.get(
          `python/envoapi/_generated/api/default/${mod}.py`,
        );
        const match = source.match(/def _get_kwargs\(([\s\S]*?)\) -> dict/);
        if (!match)
          throw new Error(`Cannot find generated Python signature: ${mod}`);
        let sig = match[1].trim();
        const names = [...sig.matchAll(/^\s*(\w+):/gm)].map((m) => m[1]);
        sig = sig.replace(/\burl_query\b/g, "url");
        const imported = [
          ...source.matchAll(/from \.\.\.models\.\w+ import (\w+)/g),
        ].map((m) => m[1]);
        for (const name of imported)
          sig = sig.replace(
            new RegExp(`\\b${name}\\b`, "g"),
            `m_${mod}.${name}`,
          );
        // Leave optional query fields absent unless explicitly supplied. Backend owns defaults.
        sig = sig.replace(/(\| Unset) = [^,\n]+/g, "$1 = UNSET");
        py += `\n    ${async ? "async " : ""}def ${m.python}(self, ${sig}) -> Response[m_${mod}.${m.response}]:\n        return ${async ? "await " : ""}self._owner._request(m_${mod}.${m.response}, m_${mod}._get_kwargs(${names.map((n) => n + "=" + (n === "url_query" ? "url" : n)).join(", ")}))\n`;
      }
    }
  fs.writeFileSync(path.join(tmp, "resources.py"), py);
  run("ruff", ["format", path.join(tmp, "resources.py")]);
  put(
    "python/envoapi/resources.py",
    fs.readFileSync(path.join(tmp, "resources.py"), "utf8"),
  );
  let init = `"""EnvoAPI Python SDK. Generated resource bindings; see runtime for transport policy."""\nimport httpx as _httpx\nfrom .runtime import APIError, DecodeError, TransportError, Response\nfrom .runtime import SyncTransport, AsyncTransport\nfrom . import resources\nfrom ._generated import models\nfrom ._generated.types import UNSET, Unset\n\n`;
  for (const async of [false, true]) {
    init +=
      `class ${async ? "AsyncEnvoAPI" : "EnvoAPI"}(${async ? "Async" : "Sync"}Transport):\n    def __init__(self, *, api_key: str | None = None, base_url: str = 'https://api.envoapi.com',\n                 timeout: float | _httpx.Timeout = 60.0, transport: _httpx.${async ? "AsyncBaseTransport" : "BaseTransport"} | None = None):\n        super().__init__(api_key=api_key, base_url=base_url, timeout=timeout, transport=transport)\n` +
      groups
        .map(
          (g) =>
            `        self.${g} = resources.${async ? "Async" : ""}${upper(g)}(self)`,
        )
        .join("\n") +
      "\n\n";
  }
  put("python/envoapi/__init__.py", init.trimEnd() + "\n");

  let go =
    '// Code generated by scripts/generate.mjs. DO NOT EDIT.\npackage envoapi\n\nimport ("context";"time";"github.com/envoapi-official/envoapi-sdks/go/api")\n';
  go +=
    "type Client struct {raw *api.Client;timeout time.Duration;" +
    groups.map((g) => `${upper(g)} *${upper(g)}Service`).join(";") +
    "}\n";
  go +=
    "func(c *Client) initResources(){" +
    groups.map((g) => `c.${upper(g)}=&${upper(g)}Service{client:c}`).join(";") +
    "}\n";
  for (const group of groups) {
    go += `type ${upper(group)}Service struct {client *Client}\n`;
    for (const m of manifest.filter((m) => m.resource === group)) {
      const op = upper(m.operationId);
      go += `type ${op}Params = api.${op}Params\n`;
      go += `func(s *${upper(group)}Service) ${m.go}(ctx context.Context, params ${op}Params)(*Response[api.${m.response}],error){\nctx,cancel:=context.WithTimeout(ctx,s.client.timeout);defer cancel()\nresponse,err:=s.client.raw.${op}(ctx,&params)\nreturn decode[api.${m.response}](response,err)\n}\n`;
    }
  }
  fs.writeFileSync(path.join(tmp, "resources.go"), go);
  run("gofmt", ["-w", path.join(tmp, "resources.go")]);
  put(
    "go/resources.go",
    fs.readFileSync(path.join(tmp, "resources.go"), "utf8"),
  );
  put(
    "docs/operations.md",
    "# Operation coverage\n\nGenerated from the public contract. Python parameter names use snake_case; wire names remain unchanged.\n\n| Operation | TypeScript | Python | Go |\n|---|---|---|---|\n" +
      manifest
        .map(
          (m) =>
            `| ${m.operationId} | ${m.resource}.${m.typescript} | ${m.resource}.${m.python} | ${upper(m.resource)}.${m.go} |`,
        )
        .join("\n") +
      "\n",
  );

  const differences = [];
  for (const [relative, value] of outputs) {
    const dest = path.join(root, relative);
    if (check) {
      if (!fs.existsSync(dest) || fs.readFileSync(dest, "utf8") !== value)
        differences.push(relative);
    } else {
      fs.mkdirSync(path.dirname(dest), { recursive: true });
      fs.writeFileSync(dest, value);
    }
  }
  // Detect stale generated Python files after operations/models are removed.
  const generated = path.join(root, "python/envoapi/_generated");
  if (fs.existsSync(generated))
    for (const relative of fs.readdirSync(generated, { recursive: true })) {
      if (!relative.endsWith(".py")) continue;
      const name = "python/envoapi/_generated/" + relative;
      if (!outputs.has(name)) {
        if (check) differences.push(name);
        else fs.unlinkSync(path.join(root, name));
      }
    }
  if (differences.length)
    throw new Error("Generated files differ:\n" + differences.join("\n"));
  console.log(
    `${check ? "Verified" : "Generated"} ${manifest.length} operations in TypeScript, Python, and Go.`,
  );
} finally {
  fs.rmSync(tmp, { recursive: true, force: true });
}
